export const experiencesEn = [
  {
    id: 6,
    title: "Independent Open-Source & Product Work",
    date: "May 2026 – Present",
    type: "Independent",
    points: [
      "Built and published Vue Smart Loading Kit and new portfolio projects (see Projects), while deepening my testing practice and AI-assisted workflow.",
    ],
    link: "https://github.com/navidjaberi",
    skills: ["Vue 3", "TypeScript", "Next.js", "Vitest", "Playwright"],
  },
  {
    id: 5,
    title: "Frontend Developer — Dongi",
    date: "Nov 2025 – May 2026",
    type: "Full-time · Remote",
    points: [
      "Built core features of an internal CRM (Nuxt 3, Vuetify, Tailwind CSS) used daily by 50+ employees, including data tables with complex, combinable filters, working with backend developers on the REST APIs behind them.",
      "Improved technical SEO on Dongi's main site, a server-rendered Quasar (Vue 3) app, with meta tags, semantic HTML and Schema.org structured data (Lighthouse SEO score: 100), and shipped feature work on the same codebase.",
      "Delivered work in Scrum sprints, using feature branches, pull requests and code review.",
    ],
    link: "https://dongi.ir/",
    skills: ["Nuxt 3", "Vue 3", "TypeScript", "Vuetify", "Quasar", "Tailwind CSS", "SEO", "Scrum"],
  },
  {
    id: 4,
    title: "Frontend Developer — Qman",
    date: "Jul 2024 – Jun 2026",
    type: "Part-time · Hybrid",
    points: [
      "Led frontend development of a SaaS platform for cafe and restaurant digital menus, building 3 connected Nuxt 3 apps from scratch (public site, admin panel, owner dashboard).",
      "Planned frontend tasks, reviewed a second developer's code, and turned requirements into technical tasks with a non-technical project manager.",
      "Built a menu editor whose changes publish right away to each venue's public menu on a separate domain, delivered as a PWA (TypeScript, Pinia, Tailwind CSS).",
      "Designed the client-side data layer with the backend developer and turned complex Figma designs into UI flows with the designer.",
    ],
    link: "https://qman.ir/",
    skills: ["Nuxt 3", "TypeScript", "Pinia", "Tailwind CSS", "PWA", "Code Review"],
  },
  {
    id: 3,
    title: "Freelance Frontend Developer — Mizooni",
    date: "Mar 2024 – Jun 2024",
    type: "Part-time · Remote",
    points: [
      "Built key sections of a pre-launch women's health web app with Nuxt 3, Vuetify and Tailwind CSS, working under a senior developer in a task-based workflow.",
      "Implemented a complex, animation-heavy UI with advanced visual effects, mobile-first and designed for non-technical users.",
      "Set the app up as an installable PWA, so users could add it to their home screen like a native app.",
    ],
    link: "https://mizooni.app/",
    skills: ["Nuxt 3", "Vuetify", "Tailwind CSS", "PWA"],
  },
  {
    id: 2,
    title: "Frontend Developer — Asia Salamat",
    date: "May 2023 – Jan 2024",
    type: "Full-time · On-site",
    points: [
      "Built a nurse booking PWA with TypeScript and Tailwind CSS, with responsive, accessible flows designed for elderly and non-technical users.",
      "Designed the app's frontend architecture and reusable component structure.",
      "Integrated the booking flows with the backend's healthcare scheduling logic.",
    ],
    link: "http://asiasalamat.ir/",
    skills: ["TypeScript", "Tailwind CSS", "PWA", "Accessibility"],
  },
  {
    id: 1,
    title: "Frontend Developer Intern",
    date: "2022 – 2023",
    type: "Full-time",
    points: [
      "Worked largely independently, with a senior developer mentoring me on architecture decisions and reviewing my code.",
      "Built my first Next.js project, a food ordering site with authentication, later rebuilt as Food Corner (see Projects).",
    ],
    link: "",
    skills: ["React", "Next.js"],
  },
];
