export const experiencesTr = [
  {
    id: 6,
    title: "Bağımsız Açık Kaynak ve Ürün Çalışmaları",
    date: "Mayıs 2026 – Günümüz",
    type: "Bağımsız",
    points: [
      "Vue Smart Loading Kit'i ve yeni portfolyo projelerini (bkz. Projeler) geliştirip yayınladım; bu sırada test pratiğimi ve yapay zekâ destekli çalışma düzenimi derinleştirdim.",
    ],
    link: "https://github.com/navidjaberi",
    skills: ["Vue 3", "TypeScript", "Next.js", "Vitest", "Playwright"],
  },
  {
    id: 5,
    title: "Frontend Geliştirici — Dongi",
    date: "Kasım 2025 – Mayıs 2026",
    type: "Tam zamanlı · Uzaktan",
    points: [
      "50'den fazla çalışanın her gün kullandığı dahili bir CRM'in (Nuxt 3, Vuetify, Tailwind CSS) temel özelliklerini geliştirdim; karmaşık, birleştirilebilir filtreli veri tabloları dahil, arkalarındaki REST API'ler üzerinde backend geliştiricilerle birlikte çalıştım.",
      "Sunucu tarafında render edilen bir Quasar (Vue 3) uygulaması olan Dongi'nin ana sitesinin teknik SEO'sunu meta etiketler, semantik HTML ve Schema.org yapılandırılmış verileriyle iyileştirdim (Lighthouse SEO puanı: 100) ve aynı kod tabanında yeni özellikler geliştirdim.",
      "İşleri Scrum sprintlerinde; feature branch, pull request ve kod incelemesiyle teslim ettim.",
    ],
    link: "https://dongi.ir/",
    skills: ["Nuxt 3", "Vue 3", "TypeScript", "Vuetify", "Quasar", "Tailwind CSS", "SEO", "Scrum"],
  },
  {
    id: 4,
    title: "Frontend Geliştirici — Qman",
    date: "Temmuz 2024 – Haziran 2026",
    type: "Yarı zamanlı · Hibrit",
    points: [
      "Kafe ve restoranlar için dijital menü sunan bir SaaS platformunun frontend geliştirmesini yönettim; birbirine bağlı 3 Nuxt 3 uygulamasını sıfırdan geliştirdim (genel site, yönetim paneli, işletme sahibi paneli).",
      "Frontend görevlerini planladım, ikinci bir geliştiricinin kodunu inceledim ve teknik olmayan bir proje yöneticisiyle gereksinimleri teknik görevlere dönüştürdüm.",
      "Değişiklikleri her mekânın ayrı bir alan adındaki genel menüsüne anında yayınlanan bir menü düzenleyici geliştirdim ve PWA olarak sundum (TypeScript, Pinia, Tailwind CSS).",
      "İstemci tarafı veri katmanını backend geliştiricisiyle birlikte tasarladım ve karmaşık Figma tasarımlarını tasarımcıyla birlikte arayüz akışlarına dönüştürdüm.",
    ],
    link: "https://qman.ir/",
    skills: ["Nuxt 3", "TypeScript", "Pinia", "Tailwind CSS", "PWA", "Code Review"],
  },
  {
    id: 3,
    title: "Serbest Frontend Geliştirici — Mizooni",
    date: "Mart 2024 – Haziran 2024",
    type: "Yarı zamanlı · Uzaktan",
    points: [
      "Lansman öncesi bir kadın sağlığı web uygulamasının temel bölümlerini Nuxt 3, Vuetify ve Tailwind CSS ile, kıdemli bir geliştiricinin yönetiminde görev bazlı bir akışta geliştirdim.",
      "Gelişmiş görsel efektler içeren, animasyon ağırlıklı karmaşık bir arayüzü mobil öncelikli ve teknik olmayan kullanıcılar için tasarlanmış şekilde uyguladım.",
      "Uygulamayı yüklenebilir bir PWA olarak kurdum; kullanıcılar onu yerel bir uygulama gibi ana ekranlarına ekleyebildi.",
    ],
    link: "https://mizooni.app/",
    skills: ["Nuxt 3", "Vuetify", "Tailwind CSS", "PWA"],
  },
  {
    id: 2,
    title: "Frontend Geliştirici — Asia Salamat",
    date: "Mayıs 2023 – Ocak 2024",
    type: "Tam zamanlı · Ofiste",
    points: [
      "Yaşlı ve teknik olmayan kullanıcılar için tasarlanmış duyarlı ve erişilebilir akışlara sahip bir hemşire randevu PWA'sını TypeScript ve Tailwind CSS ile geliştirdim.",
      "Uygulamanın frontend mimarisini ve yeniden kullanılabilir bileşen yapısını tasarladım.",
      "Randevu akışlarını backend'deki sağlık hizmeti planlama mantığıyla entegre ettim.",
    ],
    link: "http://asiasalamat.ir/",
    skills: ["TypeScript", "Tailwind CSS", "PWA", "Accessibility"],
  },
  {
    id: 1,
    title: "Frontend Geliştirici Stajyeri",
    date: "2022 – 2023",
    type: "Tam zamanlı",
    points: [
      "Büyük ölçüde bağımsız çalıştım; kıdemli bir geliştirici mimari kararlarda bana mentorluk yaptı ve kodumu inceledi.",
      "İlk Next.js projemi, kimlik doğrulamalı bir yemek sipariş sitesini geliştirdim; daha sonra onu Food Corner olarak yeniden yazdım (bkz. Projeler).",
    ],
    link: "",
    skills: ["React", "Next.js"],
  },
];
